spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev	#开发环境
  application: 
    name: microservicecloud-config-haohan-dev
---
spring: 
  profiles: dev	#测试环境
  application: 
    name: microservicecloud-config-haohan-test
#保存为UTF-8